name: "publish npm package"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
